name: Node.js install

on:
  push:
    branches: [ main, newBranch ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependenciese
        run: npm install
      - name: build typescript
        run: npm run build --if-present
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: dist/main.js
      - name: run the hello world
        run: npm start
